---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>  
`Twas brillig, and the slithy toves   
Did gyre and gimble in the wabe:    
  All mimsy were the borogoves,   
And the mome raths outgrabe.     
  
  
  "Beware the Jabberwock, my son!     
  The jaws that bite, the claws that catch!     
Beware the Jubjub bird, and shun     
  The frumious Bandersnatch!"     

## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>
Two roads diverged in a yellow wood,    
And sorry I could not travel both   
And be one traveler, long I stood    
And looked down one as far as I could    
To where it bent in the undergrowth; 

 Then took the other, as just as fair,    
And having perhaps the better claim,   
Because it was grassy and wanted wear;   
Though as for that the passing there   
Had worn them really about the same,   


## Third Verse
<Put the first two verses of The Walrus and the Carpenter here>
The sun was shining on the sea,   
Shining with all his might:   
He did his very best to make   
The billows smooth and bright--   
And this was odd, because it was   
The middle of the night.   

The moon was shining sulkily,   
Because she thought the sun  
Had got no business to be there  
After the day was done--   
"It's very rude of him," she said,   
"To come and spoil the fun!"   

## Last Verse
<Put a short poem of your choice 8-20 lines,here> 

A Dream by Edgar Allan Poe    
 In visions of the dark night   
I have dreamed of joy departed-    
But a waking dream of life and light  
Hath left me broken-hearted.  

Ah! what is not a dream by day   
To him whose eyes are cast  
On things around him with a ray  
Turned back upon the past?   

That holy dream- that holy dream,  
While all the world were chiding,  
Hath cheered me as a lovely beam  
A lonely spirit guiding.  

What though that light, thro' storm and night,  
So trembled from afar-   
What could there be more purely bright   
In Truth's day-star?    

